
direction: right

style {
    fill: transparent 
}

classes: {
  rare: {
    shape: image
    icon: https://raw.githubusercontent.com/GEANT/rare-docs/main/docs/img/rare.svg
  }
  xrd: {
    shape: image
    icon: https://raw.githubusercontent.com/GEANT/rare-docs/main/docs/img/xrd.svg
  }
  vr-xrv9k: {
    shape: image
    icon: https://raw.githubusercontent.com/GEANT/rare-docs/main/docs/img/vr-xrv9k.svg
  }
  linux: {
    shape: image
    icon: https://raw.githubusercontent.com/GEANT/rare-docs/main/docs/img/linux.svg
  }
  crpd: {
    shape: image
    icon: https://raw.githubusercontent.com/GEANT/rare-docs/main/docs/img/crpd.svg
  }
}

r1.class: rare
r2.class: rare

r1 <-> r2: {
  source-arrowhead.label: ser1
  target-arrowhead.label: ser1
}
r1 <-> r2: {
  source-arrowhead.label: ser2
  target-arrowhead.label: ser2
}
r1 <-> r2: {
  source-arrowhead.label: ser3
  target-arrowhead.label: ser3
}
r1 <-> r2: {
  source-arrowhead.label: ser4
  target-arrowhead.label: ser4
}
