
direction: right

style {
    fill: transparent 
}

classes: {
  rare: {
    shape: image
    icon: https://raw.githubusercontent.com/GEANT/rare-docs/main/docs/img/rare.svg
  }
  xrd: {
    shape: image
    icon: https://raw.githubusercontent.com/GEANT/rare-docs/main/docs/img/xrd.svg
  }
  vr-xrv9k: {
    shape: image
    icon: https://raw.githubusercontent.com/GEANT/rare-docs/main/docs/img/vr-xrv9k.svg
  }
  linux: {
    shape: image
    icon: https://raw.githubusercontent.com/GEANT/rare-docs/main/docs/img/linux.svg
  }
  crpd: {
    shape: image
    icon: https://raw.githubusercontent.com/GEANT/rare-docs/main/docs/img/crpd.svg
  }
}

r1.class: rare
r2.class: rare
r3 nowrite.class: rare
r4 nowrite.class: rare
r5 nowrite.class: rare

r1 <-> r2: {
  source-arrowhead.label: eth1
  target-arrowhead.label: eth1
}
r2 <-> r3 nowrite: {
  source-arrowhead.label: eth2
  target-arrowhead.label: eth1
}
r2 <-> r4 nowrite: {
  source-arrowhead.label: eth3
  target-arrowhead.label: eth1
}
r2 <-> r5 nowrite: {
  source-arrowhead.label: eth4
  target-arrowhead.label: eth1
}
r2 <-> r3 nowrite: {
  source-arrowhead.label: eth31
  target-arrowhead.label: eth8
}
r2 <-> r3 nowrite: {
  source-arrowhead.label: eth32
  target-arrowhead.label: eth9
}
r2 <-> r4 nowrite: {
  source-arrowhead.label: eth41
  target-arrowhead.label: eth8
}
r2 <-> r4 nowrite: {
  source-arrowhead.label: eth42
  target-arrowhead.label: eth9
}
r2 <-> r5 nowrite: {
  source-arrowhead.label: eth51
  target-arrowhead.label: eth8
}
r2 <-> r5 nowrite: {
  source-arrowhead.label: eth52
  target-arrowhead.label: eth9
}
